### ISSUE TITLE
SteamDeck controls are not working

### ISSUE THREAD

**Issue by tzemanovic** [fishfolk/jumpy#835] opened 2023-07-08 09:19 UTC
### Description

I tried to build jumpy on SteamDeck and got it running, but unfortunately none of the input controls are being picked up. I'm not sure if it's jumpy issue or the crate that's being used for input leafwing-input-manager so still need to do more investigation.

**Comment by zicklag** [comment] 2023-07-08 13:45
Thanks for reporting! Unfortunately I don't have a steam deck to test on, so any help with this would be appreciated!

**Comment by MaxCWhitehead** [comment] 2024-01-14 05:38
I'm going to spend some time testing on steam deck, will update once I make some progress.

**Comment by MaxCWhitehead** [comment] 2024-01-17 01:44
My findings on this:

Desktop mode:
- If launched without steam, controls may be in desktop configuration. Might be able to navigate menus, but in game controls don't work.
  - Can hold the 'select' button (top left w/ two windows) to switch to gamepad config, should then work.
- If launched with steam, works as gamepad.

Game mode:
- Seems to work as intended.


There are some minor UX issues with default mappings IMO, not preventing play though, and are likely issues for all gamepads (I'll confirm and open issues separately if need be).

I think we can probably close this issue. The desktop mode controller config issue is kind of a general steam-deck gotcha if not launching through steam. Thanks for reporting it - looking forward to getting jumpy better supported on the deck.

**Comment by zicklag** [comment] 2024-01-17 15:22
Thanks for checking this out @MaxCWhitehead. I'll close this issue, though we should probably document this somewhere at some point.

**Closed by zicklag** 2024-01-17 15:22 UTC
Labels: kind:bug, help wanted
